Frontend/Controllers/ClientController.cs
using Frontend.ApiModel;
using Frontend.Helpers.Interface;
using Frontend.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Frontend.Controllers
{

    [Authorize]
    public class ClientController : Controller
    {
        IClientHelper _clientHelper;
        IAccountHelper _accountHelper;
        public ClientController(IClientHelper clientHelper)
        {
            _clientHelper = clientHelper;
        }

        public ActionResult Index()
        {
            _clientHelper.Token = HttpContext.Session.GetString("token");
            var list = _clientHelper.GetClients();
            return View(list);
        }


        public ActionResult Details(int id)
        {
            _clientHelper.Token = HttpContext.Session.GetString("token");
            var client = _clientHelper.Get(id);
            return View(client);
        }


        public ActionResult Create()
        {
            _clientHelper.Token = HttpContext.Session.GetString("token");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClientViewModel client)
        {
            try
            {
                _clientHelper.Token = HttpContext.Session.GetString("token");
                _clientHelper.Add(client);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Edit(int id)
        {
            _clientHelper.Token = HttpContext.Session.GetString("token");
            var client = _clientHelper.Get(id);
            return View(client);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClientViewModel client)
        {
            try
            {
                _clientHelper.Token = HttpContext.Session.GetString("token");
                _clientHelper.Update(client);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            _clientHelper.Token = HttpContext.Session.GetString("token");
            var client = _clientHelper.Get(id);
            return View(client);
        }

  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ClientViewModel client)
        {
            try
            {
                
                _clientHelper.Token = HttpContext.Session.GetString("token");
                _clientHelper.Delete(client.ClientId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Frontend/Controllers/EmployeeController.cs
using Frontend.ApiModel;
using Frontend.Helpers.Interface;
using Frontend.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Frontend.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        IEmployeeHelper _employeeHelper;
        IAccountHelper _accountHelper;
        public EmployeeController(IEmployeeHelper employeeHelper)
        {
            _employeeHelper = employeeHelper;
        }

        public ActionResult Index()
        {
            _employeeHelper.Token = HttpContext.Session.GetString("token");
            var list = _employeeHelper.GetEmployees();
            return View(list);
        }


        public ActionResult Details(int id)
        {
            _employeeHelper.Token = HttpContext.Session.GetString("token");
            var employee = _employeeHelper.GetEmployee(id);
            return View(employee);
        }

        public ActionResult Create()
        {
            _employeeHelper.Token = HttpContext.Session.GetString("token");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeViewModel employee)
        {
            try
            {
                _employeeHelper.Token = HttpContext.Session.GetString("token");
                _employeeHelper.AddEmployee(employee);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            _employeeHelper.Token = HttpContext.Session.GetString("token");
            var employee = _employeeHelper.GetEmployee(id);
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeViewModel employee)
        {
            try
            {
                _employeeHelper.Token = HttpContext.Session.GetString("token");
                _employeeHelper.UpdateEmployee(employee);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            _employeeHelper.Token = HttpContext.Session.GetString("token");
            var employee = _employeeHelper.GetEmployee(id);
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(EmployeeViewModel employee)
        {
            try
            {
                _employeeHelper.Token = HttpContext.Session.GetString("token");
                _employeeHelper.DeleteEmployee(employee.EmployeeID);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Frontend/Controllers/LoginController.cs
using Frontend.ApiModel;
using Microsoft.AspNetCore.Authentication.Cookies;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Frontend.Models;
using Frontend.Helpers.Interface;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Server.HttpSys;
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Authentication;
using Frontend.Helpers.Implementations;


namespace Frontend.Controllers
{
    public class LoginController : Controller
    {
        ISecurityHelper securityHelper;
        public LoginController(ISecurityHelper securityHelper)
        {
            this.securityHelper = securityHelper;
        }


        
        public IActionResult Logout()
        {
            
            HttpContext.Response.Cookies.Delete(".AspNetCore.Cookies");
            HttpContext.Response.Cookies.Delete(".AspNetCore.Session");
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Login(string ReturnedUrl = "/")
        {


            UserViewModel user = new UserViewModel();
            user.ReturnUrl = ReturnedUrl;
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserViewModel user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var loging = securityHelper.Login(user);
                    TokenAPI tokenAPI = loging.Token;
                    var loginResult = securityHelper.Login(user);
                    var EsValido = false;

                    if (tokenAPI != null)
                    {
                        HttpContext.Session.SetString("token", tokenAPI.Token);
                        EsValido = true;
                    }

                    if (!EsValido)
                    {
                        ViewBag.Message = "Invalid Credencials";
                        return View(user);
                    }

                    HttpContext.Session.SetString("userLogged", loginResult.Username);

                    var claims = new List<Claim>() {
                        new Claim(ClaimTypes.NameIdentifier, loging.Username as string),
                        new Claim(ClaimTypes.Name, loging.Username as string)
                    };

                    foreach (var item in loging.Roles)
                    {
                        claims.Add(
                        new Claim(ClaimTypes.Role, item as string)
                        );

                    }

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties()
                    {
                        IsPersistent = user.RememberLogin
                    });
                    return LocalRedirect(user.ReturnUrl);
                }


                return View(user);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

    }
}

Frontend/Controllers/RegisterController.cs
using Frontend.ApiModel;
using Frontend.Helpers.Interface;
using Frontend.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Frontend.Controllers
{
    public class RegisterController : Controller
    {

        IRegisterHelper _registerHelper;
        public RegisterController(IRegisterHelper registerHelper)
        {

            this._registerHelper = registerHelper;
        }

        public IActionResult Register()
        {
            RegisterViewModel user = new RegisterViewModel();
    
            return View(user);
        }



        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    
                    var loging = _registerHelper.RegisterUser(user);
                    
                    return RedirectToAction("Index", "Home");
                }


                return View(user);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

    }
}

Frontend/Views/Shared/_Layout.cshtml
@{
    // Verificar si el usuario está logueado y obtener sus roles
    var isAdmin = User.IsInRole("Admin");
    var isConsulta = User.IsInRole("Consulta");
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Frontend.styles.css" asp-append-version="true" />
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Banco Altum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (isConsulta || isAdmin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Cuentas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transacciones</a>
                                </li>
                            }
                            @if (isAdmin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Empleados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clientes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AccessReport" asp-action="Index">Accesos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TransactionReport" asp-action="Index">Transacciones Reportes</a>
                                </li>
                            }
                            @if (isConsulta || isAdmin)
                            {
                                <li class="nav-item" style="margin-left: auto">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>
                            }
                        } else
                        {
                            <li class="nav-item" style="margin-left: auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Iniciar Sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Register">Crear Cuenta</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>

  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="color: black">
            &copy; 2024 - Banco Altum
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>